theme = "catppuccin_mocha"

[editor]
line-number = "relative"

[editor.statusline]
left = ["mode", "spinner"]
center = []
right = ["diagnostics", "file-name", "selections", "position",   "file-type"]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]
