"$schema" = 'https://starship.rs/config-schema.json'

format = """
╭─\
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$cmd_duration\
$line_break\
╰─\
$character\
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Raspbian = "󰐿"
Macos = ""
Linux = "󰌽"
Arch = "󰣇"
Debian = "󰣚"
EndeavourOS = "󰣇"

[username]
show_always = false
style_user = "fg:pink"
style_root = "fg:maroon"
format = '[ $user ]($style)'

[directory]
style = "fg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[nodejs]
symbol = "󰎙"
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[c]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[rust]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[golang]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[php]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[java]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[kotlin]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[haskell]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[python]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:teal )]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:mantle)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '(bold fg:green)'
error_symbol = '(bold fg:red)'
vimcmd_symbol = '(bold fg:green)'
vimcmd_replace_one_symbol = '(bold fg:purple)'
vimcmd_replace_symbol = '(bold fg:purple)'
vimcmd_visual_symbol = '(bold fg:lavender)'

[git_branch]
symbol = ""
style = "fg:teal"
format = '[[ $symbol $branch ](fg:green)]($style)'

[git_status]
format     = '[$all_status]($style)'
style      = "fg:teal"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[cmd_duration]
show_milliseconds = true
format = "[ took [$duration ](bold fg:lavender)](fg:lavender)"
disabled = false
show_notifications = false
min_time_to_notify = 45000